[package]
name = "actix-web-custom-macro-example"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
actix-web-custom-macro = { path = "macro", version = "0.1" }

log = "0.4"
env_logger = "0.8"
actix-web = "3"
futures = "0.3"