[package]
name = "actix-web-custom-macro"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
log = "0.4"
quote = "1.0"
proc-macro2 = "1.0"
darling = "0.13"
syn = { version = "1.0", features = ["full", "extra-traits"] }